import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostClassifier
from flask import Flask, jsonify, redirect, request, send_from_directory
from flask_cors import CORS
from model import train_and_save_model


BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "model.cbm"
METRICS_PATH = BASE_DIR / "metrics.json"
PLOTS_DIR = BASE_DIR / "plots"
FRONTEND_DIR = BASE_DIR.parent / "frontend"
DB_PATH = BASE_DIR / "predictions.db"
DATA_PATH = BASE_DIR / "dataset.csv"

FEATURES = ["Apgar", "HeartRate", "Temperature", "RespRate", "OxygenLevel"]
DEFAULT_CLASS_LABELS = ["NEG", "EOS", "LOS"]

app = Flask(__name__)
CORS(app)

model = CatBoostClassifier()

def _metrics_need_refresh() -> bool:
    """
    If metrics were generated by an older training run (missing fields used by
    the dashboard), regenerate them.
    """

    if not METRICS_PATH.exists():
        return True
    try:
        metrics = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    except Exception:
        return True
    if not isinstance(metrics, dict) or "confusion_matrix_counts" not in metrics:
        return True
    # Refresh if new evaluation fields are missing.
    return "cv_f1_macro_mean" not in metrics or "f1_weighted" not in metrics


metrics_need_refresh = _metrics_need_refresh()

if MODEL_PATH.exists():
    model.load_model(MODEL_PATH)

if not MODEL_PATH.exists() or metrics_need_refresh:
    # Auto-train once so the demo starts even on a fresh machine.
    train_and_save_model()
    model.load_model(MODEL_PATH)


def _db_conn() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def _init_db() -> None:
    with _db_conn() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS predictions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                apgar REAL NOT NULL,
                heart_rate REAL NOT NULL,
                temperature REAL NOT NULL,
                resp_rate REAL NOT NULL,
                oxygen_level REAL NOT NULL,
                prediction INTEGER NOT NULL,
                sepsis_type TEXT,
                result TEXT NOT NULL,
                sepsis_probability REAL NOT NULL
            )
            """
        )
        # Lightweight migration for older DBs (if the table existed already).
        cols = {row["name"] for row in conn.execute("PRAGMA table_info(predictions)").fetchall()}
        if "sepsis_type" not in cols:
            conn.execute("ALTER TABLE predictions ADD COLUMN sepsis_type TEXT")
        conn.commit()


_init_db()


def _load_metrics() -> dict:
    if METRICS_PATH.exists():
        return json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    return {"accuracy": None, "confusion_matrix_image": None, "roc_curve_image": None}


def _load_class_labels() -> list[str]:
    try:
        metrics = _load_metrics()
        labels = metrics.get("class_labels")
        if isinstance(labels, list) and all(isinstance(x, str) and x for x in labels):
            return labels
    except Exception:
        pass
    return DEFAULT_CLASS_LABELS


def _coerce_label(value) -> str:
    if isinstance(value, bytes):
        try:
            return value.decode("utf-8", errors="ignore")
        except Exception:
            return str(value)
    return str(value)


def _predict_with_types(values: list[float]) -> dict:
    """
    Multiclass prediction helper for sepsis types.
    Returns:
      - pred_label: predicted class label (e.g. NEG/EOS/LOS)
      - proba_by_label: dict[label] = probability
      - any_sepsis_probability: P(EOS or LOS) if NEG exists, else max probability
    """
    labels = _load_class_labels()
    input_data = np.array([values], dtype=float)

    raw_pred = model.predict(input_data)[0]
    pred_label = _coerce_label(raw_pred).strip()

    proba = np.asarray(model.predict_proba(input_data)[0], dtype=float).ravel()
    proba_by_label = {labels[i]: float(proba[i]) for i in range(min(len(labels), len(proba)))}

    if "NEG" in labels and len(proba) == len(labels):
        any_sepsis_probability = float(1.0 - proba[labels.index("NEG")])
    elif len(proba) > 0:
        any_sepsis_probability = float(np.max(proba))
    else:
        any_sepsis_probability = 0.0

    return {
        "pred_label": pred_label,
        "proba_by_label": proba_by_label,
        "any_sepsis_probability": any_sepsis_probability,
    }


@app.get("/health")
def health():
    metrics = _load_metrics()
    return jsonify(
        {
            "status": "ok",
            "model_loaded": MODEL_PATH.exists(),
            "accuracy": metrics.get("accuracy"),
        }
    )


@app.get("/")
def home():
    return send_from_directory(FRONTEND_DIR, "index.html")


@app.get("/dashboard")
def dashboard_page():
    return redirect("/", code=302)


@app.get("/predict")
def predict_page():
    return redirect("/#predict", code=302)


@app.get("/insights")
def insights_page():
    return redirect("/#insights", code=302)


@app.get("/performance")
def performance_page():
    return redirect("/#performance", code=302)


@app.get("/dataset")
def dataset_page():
    return send_from_directory(FRONTEND_DIR, "dataset.html")


@app.get("/history")
def history_page():
    return redirect("/#history", code=302)


@app.get("/about")
def about_page():
    return send_from_directory(FRONTEND_DIR, "about.html")


@app.get("/stack")
def stack_page():
    return send_from_directory(FRONTEND_DIR, "stack.html")


@app.get("/frontend/<path:filename>")
def frontend_assets(filename: str):
    return send_from_directory(FRONTEND_DIR, filename)


@app.get("/metrics")
def metrics():
    data = _load_metrics()
    if data.get("confusion_matrix_image"):
        data["confusion_matrix_url"] = f"/{data['confusion_matrix_image']}"
    if data.get("roc_curve_image"):
        data["roc_curve_url"] = f"/{data['roc_curve_image']}"
    if data.get("feature_importance_image"):
        data["feature_importance_url"] = f"/{data['feature_importance_image']}"
    if data.get("cv_accuracy_comparison_image"):
        data["cv_accuracy_comparison_url"] = f"/{data['cv_accuracy_comparison_image']}"
    if data.get("performance_overview_image"):
        data["performance_overview_url"] = f"/{data['performance_overview_image']}"
    return jsonify(data)


@app.post("/predict")
def predict():
    payload = request.get_json(silent=True) or {}
    try:
        values = [float(payload[key]) for key in FEATURES]
    except (KeyError, TypeError, ValueError):
        return jsonify({"error": "Invalid input. Provide numeric values for all features."}), 400

    apgar, heart_rate, temperature, resp_rate, oxygen = values
    if not (0 <= apgar <= 10):
        return jsonify({"error": "Apgar must be between 0 and 10."}), 400
    if not (60 <= heart_rate <= 220):
        return jsonify({"error": "Heart Rate must be between 60 and 220 bpm."}), 400
    if not (30 <= temperature <= 43):
        return jsonify({"error": "Temperature must be between 30 and 43 deg C."}), 400
    if not (10 <= resp_rate <= 120):
        return jsonify({"error": "Respiratory Rate must be between 10 and 120."}), 400
    if not (40 <= oxygen <= 100):
        return jsonify({"error": "Oxygen Level must be between 40 and 100%."}), 400

    pred_info = _predict_with_types(values)
    pred_label = pred_info["pred_label"]
    probability_any = float(pred_info["any_sepsis_probability"])

    # Keep a binary-ish prediction for existing dashboard logic (1 = any sepsis).
    pred = 0 if pred_label == "NEG" else 1
    if pred_label == "EOS":
        result_text = "Early-onset Sepsis (EOS) risk"
    elif pred_label == "LOS":
        result_text = "Late-onset Sepsis (LOS) risk"
    else:
        result_text = "Low Risk"
    timestamp = datetime.now(timezone.utc).isoformat()
    with _db_conn() as conn:
        conn.execute(
            """
            INSERT INTO predictions
            (created_at, apgar, heart_rate, temperature, resp_rate, oxygen_level, prediction, sepsis_type, result, sepsis_probability)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                timestamp,
                apgar,
                heart_rate,
                temperature,
                resp_rate,
                oxygen,
                pred,
                pred_label,
                result_text,
                round(probability_any, 4),
            ),
        )
        conn.commit()
    return jsonify(
        {
            "prediction": pred,
            "sepsis_type": pred_label,
            "result": result_text,
            "sepsis_probability": round(probability_any, 4),
            "class_probabilities": {
                k: round(float(v), 4) for k, v in pred_info["proba_by_label"].items()
            },
            "timestamp": timestamp,
        }
    )


@app.post("/generate-alert")
def generate_alert():
    payload = request.get_json(silent=True) or {}
    try:
        values = [float(payload[key]) for key in FEATURES]
    except (KeyError, TypeError, ValueError):
        return jsonify({"error": "Invalid input. Provide numeric values for all features."}), 400

    apgar, heart_rate, temperature, resp_rate, oxygen = values
    pred_info = _predict_with_types(values)
    pred_label = pred_info["pred_label"]
    probability = float(pred_info["any_sepsis_probability"])
    pred = 0 if pred_label == "NEG" else 1

    if probability > 0.75:
        alert_level = "High"
        alert_message = (
            "High risk of sepsis detected. Immediate neonatal review, sepsis workup, and close monitoring are recommended."
        )
    elif probability >= 0.4:
        alert_level = "Medium"
        alert_message = (
            "Moderate sepsis risk detected. Increase observation frequency and consider laboratory screening."
        )
    else:
        alert_level = "Low"
        alert_message = (
            "Low sepsis risk detected. Continue routine monitoring and standard neonatal care."
        )

    if temperature >= 38.0:
        alert_message += " Fever is present."
    if oxygen < 92:
        alert_message += " Oxygen saturation is reduced."
    if resp_rate > 60:
        alert_message += " Respiratory rate is elevated."
    if apgar < 7:
        alert_message += " Apgar score is below ideal range."

    timestamp = datetime.now(timezone.utc).isoformat()
    with _db_conn() as conn:
        conn.execute(
            """
            INSERT INTO predictions
            (created_at, apgar, heart_rate, temperature, resp_rate, oxygen_level, prediction, sepsis_type, result, sepsis_probability)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                timestamp,
                apgar,
                heart_rate,
                temperature,
                resp_rate,
                oxygen,
                pred,
                pred_label,
                (
                    "Early-onset Sepsis (EOS) risk"
                    if pred_label == "EOS"
                    else ("Late-onset Sepsis (LOS) risk" if pred_label == "LOS" else "Low Risk")
                ),
                round(probability, 4),
            ),
        )
        conn.commit()

    return jsonify(
        {
            "prediction": pred,
            "sepsis_type": pred_label,
            "result": (
                "Early-onset Sepsis (EOS) risk"
                if pred_label == "EOS"
                else ("Late-onset Sepsis (LOS) risk" if pred_label == "LOS" else "Low Risk")
            ),
            "sepsis_probability": round(probability, 4),
            "alert_level": alert_level,
            "alert_message": alert_message,
            "class_probabilities": {
                k: round(float(v), 4) for k, v in pred_info["proba_by_label"].items()
            },
            "timestamp": timestamp,
        }
    )


@app.get("/prediction-summary")
def prediction_summary():
    with _db_conn() as conn:
        total_predictions = conn.execute("SELECT COUNT(*) AS c FROM predictions").fetchone()["c"]
        high_count = conn.execute(
            "SELECT COUNT(*) AS c FROM predictions WHERE prediction = 1"
        ).fetchone()["c"]
        low_count = conn.execute(
            "SELECT COUNT(*) AS c FROM predictions WHERE prediction = 0"
        ).fetchone()["c"]
        rows = conn.execute(
            """
            SELECT sepsis_probability
            FROM predictions
            ORDER BY id DESC
            LIMIT 10
            """
        ).fetchall()

    last_probabilities = [float(row["sepsis_probability"]) for row in reversed(rows)]
    last_labels = [f"P{i + 1}" for i in range(len(last_probabilities))]
    return jsonify(
        {
            "total_predictions": total_predictions,
            "high_risk_count": high_count,
            "low_risk_count": low_count,
            "last_probabilities": last_probabilities,
            "last_probability_labels": last_labels,
        }
    )


@app.get("/predictions")
def get_predictions():
    with _db_conn() as conn:
        rows = conn.execute(
            """
            SELECT id, created_at, apgar, heart_rate, temperature, resp_rate, oxygen_level, sepsis_type, result, sepsis_probability
            FROM predictions
            ORDER BY id DESC
            LIMIT 25
            """
        ).fetchall()
    return jsonify([dict(row) for row in rows])


@app.get("/dataset-analytics")
def dataset_analytics():
    if not DATA_PATH.exists():
        return jsonify({"error": "Dataset not found. Run model training first."}), 404

    df = pd.read_csv(DATA_PATH)
    output_counts = df["Output"].value_counts().to_dict()

    feature_histograms = {}
    feature_ranges = {
        "Apgar": (0, 10),
        "HeartRate": (90, 220),
        "Temperature": (34, 42),
        "RespRate": (20, 100),
        "OxygenLevel": (60, 100),
    }

    for feature, (min_v, max_v) in feature_ranges.items():
        counts, bin_edges = np.histogram(df[feature], bins=10, range=(min_v, max_v))
        labels = [f"{bin_edges[i]:.1f}-{bin_edges[i + 1]:.1f}" for i in range(len(bin_edges) - 1)]
        feature_histograms[feature] = {"labels": labels, "counts": counts.tolist()}

    return jsonify(
        {
            "sample_count": int(len(df)),
            "output_distribution": {
                "neg": int(output_counts.get("NEG", 0)),
                "eos": int(output_counts.get("EOS", 0)),
                "los": int(output_counts.get("LOS", 0)),
                "any_sepsis": int(output_counts.get("EOS", 0)) + int(output_counts.get("LOS", 0)),
            },
            "feature_histograms": feature_histograms,
        }
    )


@app.get("/dataset-preview")
def dataset_preview():
    if not DATA_PATH.exists():
        return jsonify({"error": "Dataset not found. Run model training first."}), 404

    try:
        limit = int(request.args.get("limit", 10))
    except (TypeError, ValueError):
        limit = 10
    limit = max(1, min(limit, 50))

    df = pd.read_csv(DATA_PATH).head(limit)
    rows = df.to_dict(orient="records")
    return jsonify({"columns": list(df.columns), "rows": rows, "count": int(len(rows))})


@app.get("/plots/<path:filename>")
def plot_files(filename: str):
    return send_from_directory(PLOTS_DIR, filename)


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
